// packages/ui/Button.tsx
import { cva } from "class-variance-authority"

interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: "primary" | "secondary"
  size?: "small" | "big"
  icon?: boolean
}

export function Button(props: React.PropsWithChildren<ButtonProps>) {
  const button = cva(["rounded-md", props.className], {
    variants: {
      variant: {
        primary: "border border-red-400",
        secondary: "hover:bg-red-300",
      },
      size: {
        small: !props.icon ? "px-1.5 py-1" : "p-1.5",
        big: !props.icon ? "px-1.5 py-1" : "p-1",
      },
    },
  })

  const { icon, variant, ...validProps } = props

  return (
    <button
      {...validProps}
      className={button({
        variant: props.variant || "primary",
        size: props.size || "small",
      })}
    >
      {props.children}
    </button>
  )
}

// src/components/Button.svelte
<script lang="ts">
  import { cva, type VariantProps } from "class-variance-authority";
  import type { HTMLButtonAttributes } from "svelte/elements";

  const _cvaBtn = cva("rounded-md", {
    variants: {
      variant: {
        primary: "bg-red-300 hover:bg-red-400",
        secondary: "bg-transparent hover:bg-red-300",
      },
      size: {
        smol: "class-smol",
        beeg: "p-2",
      },
    },
    compoundVariants: [{ variant: "primary", size: "beeg" }],
  });

  interface ButtonProps
    extends HTMLButtonAttributes,
      VariantProps<typeof _cvaBtn> {}

  let { variant = "primary", size = "beeg", children,  ...otherButtonStuff }: ButtonProps = $props();
</script>

<button
  {...otherButtonStuff}
  class={_cvaBtn({ variant, size, class: otherButtonStuff.class })}
>
  {@render children?.()}
</button>
