// apps/client/src/lib/components/Button.svelte
<script lang="ts">
  import type { HTMLButtonAttributes } from "svelte/elements"
  import { cva } from "class-variance-authority"

  interface Props extends HTMLButtonAttributes {
    class: string
    icon: boolean
    size: "small" | "big"
    variant: "primary" | "secondary"
  }

  const {
    class: className,
    icon,
    children,
    size,
    variant,
    ...others
  }: Partial<Props> = $props()

  const button = cva(["rounded-md", className], {
    variants: {
      variant: {
        primary: "border border-red-400",
        secondary: "hover:bg-red-300",
      },
      size: {
        small: !icon ? "px-1.5 py-1" : "p-1.5",
        big: !icon ? "px-1.5 py-1" : "p-1",
      },
    },
  })
</script>

<button
  {...others}
  class={button({
    variant: variant || "primary",
    size: size || "small",
  })}
>
  {@render children?.()}
</button>

// packages/ui/Button.tsx
import { cva } from "class-variance-authority"

interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: "primary" | "secondary"
  size?: "small" | "big"
  icon?: boolean
}

export function Button(props: React.PropsWithChildren<ButtonProps>) {
  const button = cva(["rounded-md", props.className], {
    variants: {
      variant: {
        primary: "border border-red-400",
        secondary: "hover:bg-red-300",
      },
      size: {
        small: !props.icon ? "px-1.5 py-1" : "p-1.5",
        big: !props.icon ? "px-1.5 py-1" : "p-1",
      },
    },
  })

  const { icon, variant, ...validProps } = props

  return (
    <button
      {...validProps}
      className={button({
        variant: props.variant || "primary",
        size: props.size || "small",
      })}
    >
      {props.children}
    </button>
  )
}
